services:
  web:
    image: docapp
    build:
      context: .
      dockerfile: DocApp/Dockerfile
    ports:
      - "8080:9000"
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_HTTP_PORTS=9000
#      - ASPNETCORE_HTTPS_PORTS=443;8081
  postgres:
    image: postgres:latest
    ports:
      - "5000:5432"
    environment:
        - POSTGRES_PASSWORD=1234
        - POSTGRES_USER=postgres
        - POSTGRES_DB=gravity_books
    volumes:
        - postgres-data:/var/lib/postgresql/data
        - ./sqlscripts:/docker-entrypoint-initdb.d
volumes:
  postgres-data: