services:
  web:
    image: docapp
    build:
      context: .
      dockerfile: DocApp/Dockerfile
    ports:
      - 8080:9000
      - 8081:8081
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_HTTP_PORTS=9000
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=1234
  postgres:
    image: postgres:latest
    ports:
      - "5000:5432"
    environment:
        - POSTGRES_PASSWORD=1234
        - POSTGRES_USER=postgres
        - POSTGRES_DB=gravity_books
    volumes:
        - postgres-data:/var/lib/postgresql/data
        - ./sqlscripts:/docker-entrypoint-initdb.d
  statistic:
    image: statistic
    build:
      dockerfile: StatisticService/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
      - web
volumes:
  postgres-data:
    
networks:
  rabbitmq_net:
    driver: bridge